apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: dmart-app
data:
     .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiZG90bmV0dm0xLmF6dXJlY3IuaW8iOiB7CiAgICAgICAgInVzZXJuYW1lIjogImRvdG5ldHZtMSIsCiAgICAgICAgInBhc3N3b3JkIjogIlFqZDVaRWR5T1RGUWVYSmlXbGx1UTNWbGFrWmhZMkpuVW5WdEwyUlBNRlJrVVdacVVVbHdlV3BTSzBGRFVrUjNSM1ozU1E9PSIsCiAgICAgICAgImVtYWlsIjogImF2aW5hc2g5Nz
type: kubernetes.io/dockerconfigjson
